<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="14" passed="0" failed="0" skipped="14">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-04-18T04:31:49Z" name="Auction Automation suite" finished-at="2019-04-18T04:31:54Z" duration-ms="4991">
    <groups>
    </groups>
    <test started-at="2019-04-18T04:31:49Z" name="Login Test cases" finished-at="2019-04-18T04:31:54Z" duration-ms="4991">
      <class name="org.kale.auction.Test_Cases_Modules.NOC_1">
        <test-method is-config="true" signature="intialization()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:49Z" name="intialization" finished-at="2019-04-18T10:01:54Z" duration-ms="4933" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialization -->
        <test-method is-config="true" signature="ReadData_UserDetails()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="ReadData_UserDetails" finished-at="2019-04-18T10:01:54Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.kale.auction.utils.WriteExcel.autoexcel(WriteExcel.java:53)
	at org.kale.auction.utils.WriteExcel.foldercreate(WriteExcel.java:40)
	at org.kale.auction.Test_Cases_Modules.NOC_1.ReadData_UserDetails(NOC_1.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadData_UserDetails -->
        <test-method is-config="true" signature="ReadData_LineNoDetails()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="ReadData_LineNoDetails" finished-at="2019-04-18T10:01:54Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadData_LineNoDetails -->
        <test-method signature="NOC1_SaveNOC1_GeneralCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_SaveNOC1_GeneralCargo" finished-at="2019-04-18T10:01:54Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_SaveNOC1_GeneralCargo -->
        <test-method signature="NOC1_Save_Abandon_GeneralCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_Save_Abandon_GeneralCargo" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_SaveNOC1_GeneralCargo" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_Save_Abandon_GeneralCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Save_Abandon_GeneralCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_Save_Abandon_GeneralCargo -->
        <test-method signature="NOC1_Save_Before30Days_NotAllow()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_Save_Before30Days_NotAllow" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_Save_Abandon_GeneralCargo" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_Save_Before30Days_NotAllow()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Save_Before30Days_NotAllow()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_Save_Before30Days_NotAllow -->
        <test-method signature="NOC1_SaveNOC1_PerishableCargo_Before_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_SaveNOC1_PerishableCargo_Before_7_Days" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_SaveNOC1_PerishableCargo_After_7_Days" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_SaveNOC1_PerishableCargo_Before_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_SaveNOC1_PerishableCargo_Before_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_SaveNOC1_PerishableCargo_Before_7_Days -->
        <test-method signature="NOC1_SaveNOC1_PerishableCargo_After_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_SaveNOC1_PerishableCargo_After_7_Days" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_Save_Before30Days_NotAllow" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_SaveNOC1_PerishableCargo_After_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_SaveNOC1_PerishableCargo_After_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_SaveNOC1_PerishableCargo_After_7_Days -->
        <test-method signature="NOC1_Save_Abandon_PerishableCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_Save_Abandon_PerishableCargo" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_SaveNOC1_PerishableCargo_Before_7_Days" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_Save_Abandon_PerishableCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Save_Abandon_PerishableCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_Save_Abandon_PerishableCargo -->
        <test-method signature="NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.Redirect_NOC1_to_UCCDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard -->
        <test-method signature="Redirect_NOC1_to_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="Redirect_NOC1_to_UCCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_Edit" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.Redirect_NOC1_to_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.Redirect_NOC1_to_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Redirect_NOC1_to_UCCDashboard -->
        <test-method signature="NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard -->
        <test-method signature="NOC1_Edit()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_Edit" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_Save_Abandon_PerishableCargo" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_Edit()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Edit()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_Edit -->
        <test-method signature="NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard -->
        <test-method signature="NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard -->
        <test-method signature="NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard -->
        <test-method signature="NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303]" started-at="2019-04-18T10:01:54Z" name="NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard" finished-at="2019-04-18T10:01:54Z" depends-on-methods="org.kale.auction.Test_Cases_Modules.NOC_1.NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NOC_1.NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard -->
      </class> <!-- org.kale.auction.Test_Cases_Modules.NOC_1 -->
    </test> <!-- Login Test cases -->
  </suite> <!-- Auction Automation suite -->
</testng-results>
