<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jitesh-dev" failures="0" tests="14" name="org.kale.auction.Test_Cases_Modules.NOC_1" time="0.000" errors="14" timestamp="18 Apr 2019 04:31:54 GMT">
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_Save_Before30Days_NotAllow" time="0.000">
    <error message="Method NOC_1.NOC1_Save_Before30Days_NotAllow()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Save_Before30Days_NotAllow()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_Save_Before30Days_NotAllow -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard" time="0.000">
    <error message="Method NOC_1.NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_GroupUser_OnlyViewNotice01_From_GroupNOCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_SaveNOC1_PerishableCargo_Before_7_Days" time="0.000">
    <error message="Method NOC_1.NOC1_SaveNOC1_PerishableCargo_Before_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_SaveNOC1_PerishableCargo_Before_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_SaveNOC1_PerishableCargo_Before_7_Days -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard" time="0.000">
    <error message="Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_CustomUser_OnlyViewNotice01_From_UCCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="Redirect_NOC1_to_UCCDashboard" time="0.000">
    <error message="Method NOC_1.Redirect_NOC1_to_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.Redirect_NOC1_to_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- Redirect_NOC1_to_UCCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard" time="0.000">
    <error message="Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_CustomUser_Redirect_Notice01_To_UCCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_Edit" time="0.000">
    <error message="Method NOC_1.NOC1_Edit()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Edit()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_Edit -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard" time="0.000">
    <error message="Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_CustomUser_Redirect_Notice01_To_NOCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard" time="0.000">
    <error message="Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_CustomUser_OnlyViewNotice01_From_NOCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard" time="0.000">
    <error message="Method NOC_1.NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_GroupUser_Redirect_Notice01_To_GroupNOCDashboard -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_Save_Abandon_GeneralCargo" time="0.000">
    <error message="Method NOC_1.NOC1_Save_Abandon_GeneralCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Save_Abandon_GeneralCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_Save_Abandon_GeneralCargo -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_SaveNOC1_PerishableCargo_After_7_Days" time="0.000">
    <error message="Method NOC_1.NOC1_SaveNOC1_PerishableCargo_After_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_SaveNOC1_PerishableCargo_After_7_Days()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_SaveNOC1_PerishableCargo_After_7_Days -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_Save_Abandon_PerishableCargo" time="0.000">
    <error message="Method NOC_1.NOC1_Save_Abandon_PerishableCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method NOC_1.NOC1_Save_Abandon_PerishableCargo()[pri:0, instance:org.kale.auction.Test_Cases_Modules.NOC_1@74e52303] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_Save_Abandon_PerishableCargo -->
  <testcase classname="org.kale.auction.Test_Cases_Modules.NOC_1" name="NOC1_SaveNOC1_GeneralCargo" time="0.000">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.kale.auction.utils.WriteExcel.autoexcel(WriteExcel.java:53)
	at org.kale.auction.utils.WriteExcel.foldercreate(WriteExcel.java:40)
	at org.kale.auction.Test_Cases_Modules.NOC_1.ReadData_UserDetails(NOC_1.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- NOC1_SaveNOC1_GeneralCargo -->
</testsuite> <!-- org.kale.auction.Test_Cases_Modules.NOC_1 -->
